const fs = require('fs');
const path = './docs/afaq_v4_complete_workflow.json';
const wf = JSON.parse(fs.readFileSync(path, 'utf8'));

// 1. Remove the direct connection from Detect Intent to Prepare Conversation Body
if (wf.connections['Detect Intent & Create Record']) {
  const detectMain = wf.connections['Detect Intent & Create Record'].main[0];
  // Filter out any connection to Prepare Conversation Body or Human Handoff?
  wf.connections['Detect Intent & Create Record'].main[0] = detectMain.filter(c => 
    c.node !== 'Prepare Conversation Body' && c.node !== 'Human Handoff?'
  );
}

// Ensure Should Write Record? FALSE branch (index 1) goes to Prepare Conversation Body
if (wf.connections['Should Write Record?']) {
  const trueBranch = wf.connections['Should Write Record?'].main[0] || [];
  const falseBranch = [{ node: 'Prepare Conversation Body', type: 'main', index: 0 }];
  wf.connections['Should Write Record?'].main = [trueBranch, falseBranch];
}

// 2. Add ?on_conflict=conversation_id to Insert nodes
const insertNodes = ['Insert Order', 'Insert Appointment', 'Insert Lead'];
insertNodes.forEach(name => {
  const node = wf.nodes.find(n => n.name === name);
  if (node && node.parameters && node.parameters.url) {
    if (!node.parameters.url.includes('on_conflict=conversation_id')) {
      node.parameters.url += '?on_conflict=conversation_id';
    }
  }
});

// 3. Update Detect Intent & Create Record code
const detectNode = wf.nodes.find(n => n.name === 'Detect Intent & Create Record');
if (detectNode) {
  detectNode.parameters.jsCode = `// ─────────────────────────────────────────────
// NODE: Detect Intent & Create Record
// ─────────────────────────────────────────────
const ctx = $('Extract AI Reply').first().json;
const msg = ctx.message || ctx.normalized_message || '';
const msgLower = msg.toLowerCase();
const aiReply = ctx.ai_reply || '';

// Use the exact intent tag generated by the AI
const intent = ctx.ai_intent || 'general_inquiry';
const previousInfo = {}; 

let createRecord = false;
let recordType = null;
let recordData = { ...previousInfo };
const niche = ctx.niche || 'general';

if (['ecommerce', 'restaurant'].includes(niche)) {
  const orderTriggerIntents = ['product_inquiry', 'order_placed', 'address_provided', 'order_confirmed', 'checkout_intent'];
  const shouldCreateOrder = orderTriggerIntents.includes(intent);

  if (shouldCreateOrder) {
    createRecord = true;
    recordType = 'order';

    let extractedItems = [];
    const cleanName = s => s.trim().replace(/\\s+/g, ' ').replace(/^(i want|mujhe|muje|mjhe|chahiye|chahie|chaie|order|please|kindly)\\s+/gi, '').trim();

    // Parse product name from Customer message
    const patA = /(\\d+)\\s*(?:pack|packs|piece|pieces|pcs|pc|item|items|x)\\s+(?:of\\s+)?([a-zA-Z0-9][a-zA-Z0-9\\s\\-\\.\\s]{2,50}?)(?=\\s*(?:chaie|chahiye|chahie|order|deliver|pkr|rs|\\.|,|$|\\n))/gi;
    const patC = /(?:i\\s+want|i\\s+need|i\\s+would\\s+like|send\\s+me|give\\s+me)\\s+([a-zA-Z0-9][a-zA-Z0-9\\s\\-\\.\\s]{1,50}?)\\s+(\\d+)\\s*(?:pack|packs|piece|pieces|pcs|pc|item|items)/gi;
    const patD = /(?:mujhe|muje|mjhe|mjhay)\\s+([a-zA-Z0-9][a-zA-Z0-9\\s\\-\\.\\s]{2,50}?)(?:\\s+chaie|\\s+chahiye|\\s+chahie|\\s+chahiyen|\\s+lena|\\s+order)/gi;

    patC.lastIndex = 0;
    const matchesC = [...msg.matchAll(patC)];
    if (matchesC.length > 0) extractedItems = matchesC.map(m => ({ name: cleanName(m[1] || ''), qty: parseInt(m[2]) || 1, price: 0 }));
    
    if (extractedItems.length === 0) {
      patA.lastIndex = 0;
      const matchesA = [...msg.matchAll(patA)];
      if (matchesA.length > 0) extractedItems = matchesA.map(m => ({ name: cleanName(m[2] || ''), qty: parseInt(m[1]) || 1, price: 0 }));
    }
    
    if (extractedItems.length === 0) {
      patD.lastIndex = 0;
      const matchesD = [...msg.matchAll(patD)];
      if (matchesD.length > 0) extractedItems = matchesD.map(m => ({ name: cleanName(m[1] || ''), qty: 1, price: 0 }));
    }

    // AI Fallback parsing: If customer message was just "COD", fetch product from AI summary
    const aiProductMatch = aiReply.match(/\\*[Pp]roduct\\*\\s*[:\\-]\\s*([^\\n]+)/);
    const aiQtyMatch = aiReply.match(/\\*[Qq]uantity\\*\\s*[:\\-]\\s*(\\d+)/);
    
    if (extractedItems.length === 0 && aiProductMatch) {
      extractedItems = [{ 
        name: cleanName(aiProductMatch[1]), 
        qty: aiQtyMatch ? parseInt(aiQtyMatch[1]) : 1, 
        price: 0 
      }];
    }

    const unitPriceMatch = aiReply.match(/(?:PKR|Rs\\.?|pkr)\\s*([\\d,]+)\\s*(?:\\/pack|\\/piece|\\/pcs|each)/i);
    const totalMatch = aiReply.match(/\\*{0,2}[Tt]otal\\*{0,2}\\s*[:\\-]\\s*(?:PKR|Rs\\.?|pkr)\\s*([\\d,]+)/i);

    let unitPrice = unitPriceMatch ? parseInt(unitPriceMatch[1].replace(/,/g, '')) : 0;
    let orderTotal = totalMatch ? parseInt(totalMatch[1].replace(/,/g, '')) : 0;

    if (extractedItems.length > 0) {
      if (unitPrice > 0) extractedItems[0].price = unitPrice;
      else if (orderTotal > 0 && extractedItems[0].qty > 0) {
        extractedItems[0].price = Math.round(orderTotal / extractedItems[0].qty);
      }
    }

    let currentItems = extractedItems.length > 0 ? extractedItems : [{ name: 'Item from chat', qty: 1, price: 0 }];

    let deliveryAddress = recordData.delivery_address || null;
    const combinedForAddr = msg + ' ' + aiReply;
    const addrLabelMatch = combinedForAddr.match(/(?:[Dd]elivery\\s+[Aa]ddress|[Dd]eliver\\s+to)\\s*[:\\-]?\\s*([^\\n,\\.]{8,100})/i);
    if (addrLabelMatch && (!deliveryAddress || intent === 'address_provided')) {
      deliveryAddress = addrLabelMatch[1].trim();
    }
    if (!deliveryAddress) {
      const addrKeywords = /\\b(dha|clifton|gulshan|phase|block|street|road|avenue|lane|sector|town|garden|colony|defence|bahria|nazimabad|korangi|malir|johar|askari|highway|rd\\b)/i;
      const addrMatch = combinedForAddr.match(new RegExp(\`[\\\\w\\\\s,\\\\.\\\\-\\\\/]{0,30}\${addrKeywords.source}[\\\\w\\\\s,\\\\.\\\\-\\\\/]{0,40}\`, 'i'));
      if (addrMatch) deliveryAddress = addrMatch[0].trim();
    }

    let paymentMethod = recordData.payment_method || null;
    if (!paymentMethod) {
      const combined = msgLower + ' ' + aiReply.toLowerCase();
      if (/\\bcod\\b|cash\\s+on\\s+delivery/.test(combined)) paymentMethod = 'COD';
      else if (/easypaisa/.test(combined)) paymentMethod = 'Easypaisa';
      else if (/jazzcash/.test(combined)) paymentMethod = 'JazzCash';
      else if (/bank\\s*transfer/.test(combined)) paymentMethod = 'Bank Transfer';
    }

    const calculatedTotal = orderTotal > 0 ? orderTotal : currentItems.reduce((s, i) => s + ((i.price || 0) * (i.qty || 1)), 0);

    const aiConfirmed = /confirm ho gaya|order confirm|order placed|confirmed your order|order ki tayari|order accept/i.test(aiReply);
    let newStatus;
    if (intent === 'order_confirmed' || aiConfirmed) {
      newStatus = 'confirmed';
    } else if (deliveryAddress && paymentMethod) {
      newStatus = 'pending';
    } else if (deliveryAddress || intent === 'address_provided') {
      newStatus = 'pending';
    } else {
      newStatus = 'pending_address';
    }

    recordData = {
      ...recordData,
      tenant_id: ctx.tenant_id,
      conversation_id: ctx.conversation_id,
      customer_phone: ctx.customer_phone,
      customer_name: ctx.customer_name,
      niche: niche,
      items: currentItems,
      order_amount: calculatedTotal,
      payment_method: paymentMethod,
      delivery_address: deliveryAddress,
      source: ctx.platform || 'whatsapp',
      handled_by: 'bot',
      status: newStatus,
    };

    if (intent === 'order_confirmed' || aiConfirmed) {
      recordData.confirmed_at = new Date().toISOString();
    }
  }
}

const needs_human_handoff = /human|agent|representative|insaan|baat|connect|transfer/i.test(msgLower);

return [{
  json: {
    ...ctx,
    detected_intent: intent,
    create_record: createRecord,
    record_type: recordType,
    record_data: recordData,
    needs_human_handoff: needs_human_handoff
  }
}];`;
}

// 4. Update Extract AI Reply
const extractNode = wf.nodes.find(n => n.name === 'Extract AI Reply');
if (extractNode) {
  extractNode.parameters.jsCode = `const response = $input.first().json;
const ctx      = $('Build AI Prompt').first().json;

if (!response.choices || !response.choices[0]) {
  throw new Error('GPT returned no response: ' + JSON.stringify(response).slice(0, 300));
}

const raw_reply = response.choices[0].message.content;

// Extract intent tag
let ai_intent = 'general_inquiry';
const intentMatch = raw_reply.match(/Intent:\\s*([a-zA-Z0-9_]+)/i);
if (intentMatch) {
  ai_intent = intentMatch[1].toLowerCase();
}

const ai_reply  = raw_reply.replace(/Intent:.*$/im, '').trim();

const prompt_tokens     = response.usage?.prompt_tokens    || 0;
const completion_tokens = response.usage?.completion_tokens || 0;
const latency_ms        = Date.now() - new Date(ctx.processed_at).getTime();

return [{
  json: {
    ...ctx,
    ai_reply,
    ai_intent,
    prompt_tokens,
    completion_tokens,
    latency_ms
  }
}];`;
}

fs.writeFileSync(path, JSON.stringify(wf, null, 2));
console.log('Workflow fixed and saved!');
